Fix EventType card
BinaryStudioAcademy/bsa-2020-schedulia pull request #238
Opened 2020-08-25 15:56 UTC by dmitriy-uvin

2020-08-25 17:06 UTC, SerhiiKundys requested changes
We can't use " !important ". Try to fix this problem in another way

2020-08-26 09:07 UTC, yevhen-turovets approved these changes
Good work )

2020-08-26 10:02 UTC, yevhen-turovets approved these changes

2020-08-26 10:04 UTC, aLLeXUs approved these changes

2020-08-26 10:05 UTC, merged