Feature/social auth
BinaryStudioAcademy/bsa-2020-schedulia pull request #259
Opened 2020-08-27 21:03 UTC by andytrue7

2020-08-28 08:03 UTC, aLLeXUs requested changes

2020-08-28 08:03 UTC, aLLeXUs commented on api/app/Http/Controllers/Auth/SocialAuthController.php
> +        return redirect(env('CLIENT_APP_URL') . '/auth/social-callback?token=' . $response);
You should also pass the provider.

2020-08-28 08:03 UTC, aLLeXUs commented on api/config/services.php
> -        'redirect_uri' => env('GOOGLE_OAUTH_REDIRECT_URI'),
Removing this you will probably break the calendar functionality.

2020-08-28 08:03 UTC, aLLeXUs commented on api/database/migrations/2020_08_20_213138_add_social_accounts_table.php
> +            $table->timestamp('expires_in')->nullable();
Changing existing migration will not have an effect because it is already applied. Also, the provider id can not be null.

2020-08-29 13:11 UTC, aLLeXUs commented on api/app/Http/Controllers/Auth/SocialAuthController.php
> +        $response = $this->action->execute($provider);
You should follow project architecture and create ActionRequest and ActionResponse DTOs.

2020-08-29 16:10 UTC, yevhen-turovets reviewed
I added comments, but I can't add comment to images. Why you don`t use svg?

2020-08-29 16:10 UTC, yevhen-turovets commented on api/app/Actions/Auth/SocialAuthResponse.php
> +
Why you don't do `declare(strict_types=1);`

2020-08-29 16:10 UTC, yevhen-turovets commented on api/database/migrations/2020_08_29_094025_change_account_id_to_string.php
> +            //
Where is a down function?

2020-08-29 16:10 UTC, yevhen-turovets commented on api/database/migrations/2020_08_29_103827_change_refresh_token_to_nullable.php
> +            //
Where is the down function?

2020-08-29 16:10 UTC, yevhen-turovets commented on client/src/components/auth/SocialLoginCallback.vue
> +        <p>Please wait while we're logging you in...</p>
Use language variable

2020-08-29 16:10 UTC, yevhen-turovets commented on api/app/Actions/Auth/SocialAuthAction.php
> +    protected function findOrCreateUser($provider, $socialUser)
Why you use the protected methods? Can better use private methods?

2020-08-29 19:45 UTC, yevhen-turovets reviewed
I don`t see Ukrainian translation

2020-08-30 00:06 UTC, yevhen-turovets approved these changes
Good work 💪

2020-08-30 06:07 UTC, aLLeXUs requested changes

2020-08-30 06:07 UTC, aLLeXUs commented on api/database/migrations/2020_08_29_094025_change_account_id_to_string.php
> +            $table->dropColumn('account_id');
The `down` method is for reverting database structure changes from the `up` method, but you are deleting column.

2020-08-30 06:07 UTC, aLLeXUs commented on api/database/migrations/2020_08_29_103827_change_refresh_token_to_nullable.php
> +            $table->dropColumn(['refresh_token', 'expires_in']);
The same here.

2020-08-30 16:09 UTC, aLLeXUs approved these changes

2020-08-30 16:09 UTC, merged