Fix displaying ownerName on public event Types page
BinaryStudioAcademy/bsa-2020-schedulia pull request #275
Opened 2020-08-29 09:39 UTC by dmitriy-uvin

2020-08-29 20:49 UTC, mv-v-7 requested changes

2020-08-29 20:49 UTC, mv-v-7 commented on client/src/views/UserEventTypesList.vue
> +                    <span>Welcome to my scheduling page.</span><br />
Please remember about localization

2020-08-29 20:49 UTC, mv-v-7 commented on client/src/views/UserEventTypesList.vue
> +                        <b>No openings at the moment.</b>
localization

2020-08-30 09:47 UTC, mv-v-7 requested changes

2020-08-30 09:47 UTC, mv-v-7 commented on client/src/store/modules/i18n/uk.js
> +    NO_OPENINGS_AT_THE_MOMENT: 'Жодного отвору на данный момент'
Жодного відкритого на даний момент

2020-08-30 10:02 UTC, mv-v-7 approved these changes

2020-08-30 12:30 UTC, yevhen-turovets approved these changes

2020-08-30 12:35 UTC, merged