Feature/scheduled events emails filter
BinaryStudioAcademy/bsa-2020-schedulia pull request #280
Opened 2020-08-30 18:56 UTC by yevhen-turovets

The task in Trello https://trello.com/c/AId9jK7b

2020-08-30 19:10 UTC, andytrue7 approved these changes

2020-08-30 19:38 UTC, mv-v-7 requested changes

2020-08-30 19:38 UTC, mv-v-7 commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
> +    color: #2c2c2c;
hard coded color constant

2020-08-30 19:38 UTC, mv-v-7 commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
>                                  background-color="rgba(224, 224, 224, 0.3)"
hardcoded color constant

2020-08-30 19:38 UTC, mv-v-7 commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
> +                                v-model="searchString"
v-model in production

2020-08-31 04:52 UTC, yevhen-turovets commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
> +    color: #2c2c2c;
no this color in constatnt

2020-08-31 04:52 UTC, yevhen-turovets commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
> +                                v-model="searchString"
no this color in constatnt

2020-08-31 05:31 UTC, yevhen-turovets commented on client/src/components/scheduled-events/Past/Filter/InviteeEmails.vue
>                                  background-color="rgba(224, 224, 224, 0.3)"
no this color in constant

2020-08-31 08:11 UTC, aLLeXUs approved these changes

2020-08-31 08:13 UTC, merged