Feature/add action event type
BinaryStudioAcademy/bsa-2020-schedulia pull request #293
Opened 2020-08-31 21:52 UTC by Zhenyok

2020-08-31 21:56 UTC, andytrue7 approved these changes

2020-09-01 07:33 UTC, aLLeXUs commented on client/src/components/events/CreateEventTypeBookingForm.vue
> +                        .tz('Europe/London')
Why the timezone hardcoded?

2020-09-01 15:08 UTC, aLLeXUs requested changes
Hardcoded timezone.

2020-09-01 20:04 UTC, andytrue7 approved these changes

2020-09-02 06:58 UTC, aLLeXUs approved these changes

2020-09-02 06:58 UTC, merged